name: Windows pack and test

on:
  push:
    branches-ignore:
      - 'pack-changes/*'
      - 'pack-changes2/*'
  pull_request:
  repository_dispatch:
  
concurrency:
  group: $win-{{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenCL driver for Intel CPU
        run: |
        
          # https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html
          Invoke-WebRequest -Uri 'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/f8f09106-6d86-41b5-83c8-02892bbb7f29/w_opencl_runtime_p_2023.1.0.46319.exe' -OutFile 'D:\igfx.exe'
          
          7z x "D:\igfx.exe" -o"D:\igfx" -y
          
          D:\igfx\w_opencl_runtime_p_2023.1.0.46319.msi /quiet
          
      - name: Download and unpack Pascal compiler
        run: |
        
          Invoke-WebRequest -Uri 'https://github.com/SunSerega/pascalabcnet/releases/download/unstable/PABCNETC.zip' -OutFile 'D:\PABCNETC.zip'
          
          Expand-Archive -Path 'D:\PABCNETC.zip' -DestinationPath 'D:\PABCNETC' -Force

      - name: Download latest POCGL version
        run: |
        
          pushd D:\
          git clone -b unstable --filter=tree:0 --no-checkout https://github.com/SunSerega/POCGL.git
          pushd POCGL
          git sparse-checkout set --no-cone Modules.Packed/OpenCL.pas Modules.Packed/OpenCLABC.pas
          git sparse-checkout list
          git checkout
          #Remove-Item -Path '.git' -Recurse -Force  
          popd
          popd
          
      - name: PackAll
        run: |
        
          Start-Process -FilePath 'D:\PABCNETC\pabcnetcclear.exe' -ArgumentList '"/SearchDir:D:\POCGL\Modules.Packed" "test OpenCL.pas"' -Wait -NoNewWindow
          Start-Process -FilePath 'test OpenCL.exe' -Wait -NoNewWindow
          
          #Get-ChildItem -File -Recurse | ForEach-Object { $_.FullName -replace [regex]::Escape((Get-Location).Path + '\'), '' } | Out-File -Append -FilePath "test otp.txt"
          
      - name: Check for changes
        run: |
        
          git push origin --delete "win-pack-changes/$(git rev-parse --abbrev-ref HEAD)" > nul 2>&1
          if ($?) {
            Write-Host "Old changes branch deleted"
          } else {
            Write-Host "Old changes branch not found"
          }
          
          if ((git diff --name-only) -or (git ls-files --others --exclude-standard)) {
            Write-Host "Changes detected"
            git checkout -B "win-pack-changes/$(git rev-parse --abbrev-ref HEAD)"
  
            #git add -u
            git add -A
            git config --global user.name "sun pack bot"
            git config --global user.email "sunserega2@gmail.com"
            git commit -m "win changes"
            git push -f --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)"
          } else {
            Write-Host "No changes detected"
          }
  